# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

editor: vim
model: ollama:gemini-3-flash-preview:latest
clients:
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  models:
  - name: deepseek-v3.1:671b-cloud
  - name: deepseek-v3.2:cloud
  - name: gemini-3-flash-preview:cloud
  - name: gemini-3-flash-preview:latest
  - name: gemini-3-pro-preview:latest
  - name: nemotron-3-nano:30b-cloud
  - name: devstral-small-2:24b-cloud
  - name: devstral-2:123b-cloud
  - name: ministral-3:3b-cloud
  - name: ministral-3:8b-cloud
  - name: ministral-3:14b-cloud
  - name: qwen3-vl:235b-cloud
  - name: qwen3-vl:235b-instruct-cloud
  - name: gpt-oss:20b-cloud
  - name: gpt-oss:120b-cloud
  - name: qwen3-coder:480b-cloud
  - name: gemma3:4b-cloud
  - name: gemma3:12b-cloud
  - name: gemma3:27b-cloud
  - name: qwen3-next:80b-cloud
  - name: glm-4.6:cloud
  - name: glm-4.7:cloud
  - name: minimax-m2:cloud
  - name: minimax-m2.1:cloud
  - name: cogito-2.1:671b-cloud
  - name: rnj-1:8b-cloud
  - name: kimi-k2:1t-cloud
  - name: kimi-k2-thinking:cloud
  - name: mistral-large-3:675b-cloud
- type: openai-compatible
  name: ai
  api_base: https://ai.zxaicc.com/api/v1
  models:
  - name: deepseek-r1-0528
  - name: qwen3-30b-a3B-instruct-2507
  - name: jennifer
